project_id = "gmqeqhlhqhyrjquzhuzg"

[api]
enabled = true
url = "https://gmqeqhlhqhyrjquzhuzg.supabase.co"
service_role_key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdtcWVxaGxocWh5cmpxdXpodXpnIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTcwOTg5ODg0OCwiZXhwIjoyMDI1NDc0ODQ4fQ.BXx-f3OGMGHHhD3x_7YwEb3hZXBHBBPaXzZyGxHPtXY"

[functions]
[functions.create-stripe-product]
verify_jwt = true