
# Project ID for your Supabase project
project_id = "gmqeqhlhqhyrjquzhuzg"

[api]
# Port that the API server listens on
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
# Port that the DB server listens on
port = 54322
shadow_port = 54320
major_version = 15

[studio]
# Port that the Studio server listens on
port = 54323

[inbucket]
# Port that the inbucket server listens on
port = 54325
smtp_port = 54326
pop3_port = 54327

[functions]
[functions.stripe-subscription-webhook]
verify_jwt = false

[functions.send-discount-email]
verify_jwt = false

