
project_id = "gmqeqhlhqhyrjquzhuzg"

[api]
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
major_version = 15

[studio]
port = 54323

[inbucket]
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
file_size_limit = "50MiB"

[auth]
site_url = "https://www.lyxdeal.se"
additional_redirect_urls = ["https://localhost:3000", "https://www.lyxdeal.se", "https://www.lyxdeal.se/salon/update-password"]
jwt_expiry = 3600
enable_signup = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[functions.test-openness]
verify_jwt = false

[functions.debug-webhook]
verify_jwt = false

[functions.stripe-subscription-webhook]
verify_jwt = false

[functions.reset-password]
verify_jwt = false

[functions.create-admin-account]
verify_jwt = false
